### ISSUE TITLE
Hot Reload Not Working in Dockerized Hyperf Application Using hyperf/watcher

### ISSUE THREAD

**Issue by abdullah-ctl** [hyperf/watcher#28]
## Docker compose setup : 

```
hyperf-skeleton:
  container_name: hyperf
  image: hyperf/hyperf:8.3-alpine-v3.19-swoole-slim
  build:
    context: .
  volumes:
    - ./:/opt/www
  ports:
    - "9501:9501"
  working_dir: /opt/www
  command: [ "php", "bin/hyperf.php", "server:watch" ]
  environment:
    - APP_ENV=${APP_ENV}
    - SCAN_CACHEABLE=false

```

## Container Error log : 

```
hyperf             | [DEBUG] [command] Commands registered by Hyperf\Command\Listener\RegisterCommandListener
hyperf             | [DEBUG] Event Hyperf\Framework\Event\BootApplication handled by Hyperf\Command\Listener\RegisterCommandListener listener.
hyperf             | [DEBUG] Event Hyperf\Framework\Event\BootApplication handled by Hyperf\Config\Listener\RegisterPropertyHandlerListener listener.
hyperf             | [DEBUG] Event Hyperf\Framework\Event\BootApplication handled by Hyperf\Database\PgSQL\Listener\RegisterConnectionListener listener.
hyperf             | [DEBUG] Event Hyperf\Framework\Event\BootApplication handled by Hyperf\DbConnection\Listener\RegisterConnectionResolverListener listener.
hyperf             | [DEBUG] Event Hyperf\Framework\Event\BootApplication handled by Hyperf\ExceptionHandler\Listener\ExceptionHandlerListener listener.
hyperf             |                                                          
hyperf             |   No arguments expected for "start" command, got "php".  
hyperf             |                                                          
hyperf exited with code 1

```
